import { CARE } from "./care";
import { sizesBetween } from "./sizes";
import type { ProductSeed } from "./types";

/** Outerwear and accessories. */
export const LAYER_SEEDS: ProductSeed[] = [
  /* ── Outerwear ────────────────────────────────────────────────────────── */
  {
    slug: "structured-overshirt",
    code: "SOS",
    name: "Structured Overshirt",
    category: "outerwear",
    collections: ["harmattan-26", "studio-essentials"],
    summary: "A heavy cotton-twill overshirt with a firm collar and two bellowed chest pockets.",
    description:
      "Cut from a dense 340 g/m² cotton twill, peach-brushed so the face has a soft, almost suede-like surface. The collar is interfaced to stand up on its own, and the bellowed pockets carry a phone without pulling the front out of shape. It sits between shirt and jacket — the layer that goes on as the harmattan evenings cool.",
    details: [
      "Boxy fit with a straight hem",
      "Interfaced point collar",
      "Two bellowed chest pockets with button flaps",
      "Corozo buttons",
      "Side vents for ease of movement",
    ],
    material: "100% cotton twill, 340 g/m², peach-brushed",
    care: CARE.cottonHeavy,
    fit: "Boxy fit, designed to layer; take your usual size",
    modelNote: "Model is 188cm and wears M.",
    price: 118_000_00,
    badge: "new",
    isFeatured: true,
    tags: ["cotton", "twill", "overshirt", "shacket", "shirt jacket", "boxy", "layering", "workwear", "casual", "harmattan"],
    colors: ["camel", "olive", "ink"],
    sizes: sizesBetween("xs", "xxl"),
    createdAt: "2026-09-04T09:00:00.000Z",
  },
  {
    slug: "cropped-twill-jacket",
    code: "CTJ",
    name: "Cropped Twill Jacket",
    category: "outerwear",
    collections: ["harmattan-26"],
    summary: "A short, clean-fronted jacket in washed cotton twill that finishes at the waist.",
    description:
      "Cropped to meet the waistband, so it sits naturally over higher-rise trousers and keeps the proportions balanced. The twill is garment-washed to a soft, slightly faded surface, and the front closes with a concealed zip and a single snap at the collar. Light enough for the day, with just enough weight for the evening.",
    details: [
      "Cropped, boxy body finishing at the waist",
      "Concealed two-way zip with a snap-fastening collar",
      "Hidden side-seam pockets",
      "Adjustable snap tabs at the hem",
      "Unlined, with taped internal seams",
    ],
    material: "100% cotton twill, 300 g/m², garment-washed",
    care: CARE.cottonHeavy,
    fit: "Cropped and boxy; take your usual size",
    modelNote: "Model is 185cm and wears M.",
    price: 96_500_00,
    badge: "new",
    tags: ["cotton", "twill", "jacket", "cropped", "blouson", "lightweight", "layering", "casual", "harmattan"],
    colors: ["sand", "clay", "ink"],
    sizes: sizesBetween("s", "xl"),
    createdAt: "2026-08-19T09:00:00.000Z",
  },
  {
    slug: "suede-trucker-jacket",
    code: "STJ",
    name: "Suede Trucker Jacket",
    category: "outerwear",
    collections: ["harmattan-26"],
    summary: "A four-pocket trucker jacket in soft goat suede, lined in cotton.",
    description:
      "Goat suede is lighter and softer than cowhide, with a fine nap that brushes back to a deep, even colour. We kept the familiar trucker lines — pleated front panels, pointed pocket flaps, adjustable waist tabs — and lined it in cotton voile so it breathes. It marks with wear, and that is rather the point.",
    details: [
      "Regular fit, finishing at the hip",
      "Pleated front panels",
      "Two flapped chest pockets and two hand pockets",
      "Adjustable button tabs at the waist",
      "Lined in cotton voile",
    ],
    material: "100% goat suede; lining 100% cotton voile",
    care: CARE.suede,
    fit: "Regular fit; take your usual size",
    modelNote: "Model is 188cm and wears L.",
    price: 245_000_00,
    badge: "new",
    tags: ["suede", "leather", "jacket", "trucker", "outerwear", "evening", "layering", "harmattan"],
    colors: ["olive", "tobacco"],
    sizes: sizesBetween("s", "xl"),
    createdAt: "2026-09-01T09:00:00.000Z",
  },
  {
    slug: "lightweight-chore-coat",
    code: "LCC",
    name: "Lightweight Chore Coat",
    category: "outerwear",
    collections: ["studio-essentials"],
    summary: "A long, three-pocket work coat in an airy cotton and linen canvas.",
    description:
      "The shape of a traditional chore coat — straight, collared, three patch pockets — made light enough for Lagos in a loosely woven cotton and linen canvas. It falls to mid-thigh and is left unlined, with every internal seam bound so it looks as good on the hanger as it does on. Over a tee for errands, over a shirt for the office.",
    details: [
      "Straight cut, mid-thigh length",
      "Point collar with a throat latch",
      "Three patch pockets",
      "Unlined, with bound internal seams",
      "Enamelled metal buttons",
    ],
    material: "60% cotton, 40% linen canvas, 240 g/m²",
    care: CARE.cottonHeavy,
    fit: "Relaxed fit; take your usual size",
    modelNote: "Model is 186cm and wears M.",
    price: 132_000_00,
    bestsellerRank: 8,
    tags: ["cotton", "linen", "canvas", "chore coat", "jacket", "workwear", "lightweight", "layering", "essential"],
    colors: ["camel", "navy", "stone"],
    sizes: sizesBetween("s", "xxl"),
    createdAt: "2026-03-02T09:00:00.000Z",
  },

  /* ── Accessories ──────────────────────────────────────────────────────── */
  {
    slug: "leather-crossbody-bag",
    code: "LCB",
    name: "Leather Crossbody Bag",
    category: "accessories",
    collections: ["harmattan-26"],
    summary: "A compact crossbody bag in vegetable-tanned leather, with an adjustable strap.",
    description:
      "Cut from full-grain vegetable-tanned leather that darkens and polishes with handling. It is sized for the essentials — phone, cards, keys, sunglasses — with a flat back pocket for anything you need quickly. The strap adjusts to wear across the body or short on the shoulder.",
    details: [
      "Measures 22 × 16 × 6cm",
      "Magnetic flap closure over one main compartment",
      "Flat exterior back pocket",
      "Hand-painted edges",
      "Solid brass hardware",
    ],
    material: "Full-grain vegetable-tanned leather; cotton twill lining; brass hardware",
    care: CARE.leather,
    fit: "One size; the strap adjusts from 100cm to 128cm",
    modelNote: null,
    price: 135_000_00,
    isFeatured: true,
    tags: ["leather", "bag", "crossbody", "vegetable tanned", "accessories", "everyday", "travel", "gift"],
    colors: ["tobacco", "ink"],
    sizes: ["one-size"],
    createdAt: "2026-06-22T09:00:00.000Z",
  },
  {
    slug: "woven-leather-belt",
    code: "WLB",
    name: "Woven Leather Belt",
    category: "accessories",
    collections: ["studio-essentials"],
    summary: "A hand-braided leather belt with a solid brass buckle.",
    description:
      "Strips of vegetable-tanned leather are braided by hand over a cotton core, so the belt flexes and the prong can fasten anywhere along its length — no holes needed. The buckle is solid brass, left unlacquered to take on a soft patina. Narrow enough for tailoring, relaxed enough for denim.",
    details: [
      "3cm wide",
      "Hand-braided leather over a cotton core",
      "Solid unlacquered brass buckle",
      "Leather-bound tip and keeper",
      "Fastens anywhere along the weave",
    ],
    material: "Vegetable-tanned leather; solid brass buckle",
    care: CARE.leather,
    fit: "Sized in centimetres; a 32 waist usually takes an 85",
    modelNote: null,
    price: 38_500_00,
    bestsellerRank: 9,
    tags: ["leather", "belt", "braided", "woven", "brass", "accessories", "tailoring", "denim", "gift"],
    colors: ["chocolate", "ink"],
    sizes: sizesBetween("b80", "b100"),
    createdAt: "2026-05-27T09:00:00.000Z",
  },
  {
    slug: "cotton-bucket-hat",
    code: "CBH",
    name: "Cotton Bucket Hat",
    category: "accessories",
    collections: ["coastline"],
    summary: "A soft, packable bucket hat in washed cotton canvas.",
    description:
      "Washed cotton canvas, cut with a short, gently sloping brim that shades the eyes without flopping. Fine rows of stitching keep the brim in shape, and the crown folds flat into a bag or pocket. Small eyelets at each side let the heat escape.",
    details: [
      "Short 6cm brim with eight rows of stitching",
      "Six-panel crown",
      "Two brass eyelets at each side",
      "Cotton twill sweatband",
      "Folds flat for travel",
    ],
    material: "100% cotton canvas, 280 g/m², washed",
    care: CARE.hat,
    fit: "One size; fits a 57–59cm head",
    modelNote: null,
    price: 22_500_00,
    compareAtPrice: 31_500_00,
    tags: ["cotton", "canvas", "hat", "bucket hat", "accessories", "sun", "summer", "holiday", "travel"],
    colors: ["olive", "stone"],
    sizes: ["one-size"],
    createdAt: "2026-04-10T09:00:00.000Z",
  },
];
