import { CARE } from "./care";
import { sizesBetween } from "./sizes";
import type { ProductSeed } from "./types";

/** Trousers, denim and tailoring. */
export const BOTTOM_SEEDS: ProductSeed[] = [
  /* ── Trousers ─────────────────────────────────────────────────────────── */
  {
    slug: "straight-leg-trousers",
    code: "SLT",
    name: "Straight-Leg Trousers",
    category: "trousers",
    collections: ["studio-essentials"],
    summary: "A mid-rise cotton twill trouser with a clean, straight line from hip to hem.",
    description:
      "Brushed cotton twill with a little stretch, cut flat-fronted and mid-rise, with a straight leg that meets the shoe without breaking. A pressed centre crease keeps the line sharp, and the belt loops are wide enough for a proper leather belt. As easy with a tee as with a band-collar shirt.",
    details: [
      "Mid-rise, flat front",
      "Straight leg, 20cm at the hem in a size 32",
      "Slanted side pockets and two jetted back pockets",
      "Zip fly with hook-and-bar closure",
      "Hemmed at an 82cm inside leg",
    ],
    material: "98% cotton, 2% elastane brushed twill, 290 g/m²",
    care: CARE.cottonWoven,
    fit: "Regular through the seat and thigh with a straight leg; take your usual waist size",
    modelNote: "Model is 188cm and wears 32.",
    price: 68_000_00,
    isFeatured: true,
    bestsellerRank: 3,
    tags: ["cotton", "twill", "trousers", "straight leg", "chinos", "flat front", "office", "smart", "everyday", "essential"],
    colors: ["stone", "ink", "olive"],
    sizes: sizesBetween("w28", "w38"),
    createdAt: "2026-01-14T09:00:00.000Z",
  },
  {
    slug: "pleated-wide-trousers",
    code: "PWT",
    name: "Pleated Wide Trousers",
    category: "trousers",
    collections: ["coastline"],
    summary: "High-waisted trousers with double forward pleats and a full, fluid leg.",
    description:
      "Cut from a linen and cotton twill with enough weight to fall straight and swing a little with each step. Two deep forward pleats open the leg from a higher waist, and side adjusters take the place of belt loops so the waistband stays clean. They ask for a tucked shirt and a flat shoe.",
    details: [
      "High rise with double forward pleats",
      "Wide leg, 26cm at the hem in a size 32",
      "Side adjusters with metal buckles; no belt loops",
      "Extended waistband with button and hook closure",
      "Deep 5cm turn-ups",
    ],
    material: "55% linen, 45% cotton twill, 250 g/m²",
    care: CARE.linen,
    fit: "High-waisted and generous through the leg; take your usual waist size",
    modelNote: "Model is 185cm and wears 32.",
    price: 67_000_00,
    compareAtPrice: 86_000_00,
    tags: ["linen", "cotton", "trousers", "pleated", "wide leg", "high waisted", "tailored", "smart", "summer"],
    colors: ["ecru", "taupe", "ink"],
    sizes: sizesBetween("w28", "w36"),
    createdAt: "2026-03-27T09:00:00.000Z",
  },
  {
    slug: "drawstring-linen-trousers",
    code: "DLT",
    name: "Drawstring Linen Trousers",
    category: "trousers",
    collections: ["coastline"],
    summary: "A loose linen trouser with a drawstring waist and a gently tapered ankle.",
    description:
      "The same washed linen as our relaxed shirt, in a slightly heavier weight so the trousers hang rather than cling. An elasticated back waist and a flat cotton drawcord make them quick to put on, and the leg narrows gently from the knee. The pair for weekends, travel and the hottest afternoons.",
    details: [
      "Mid-rise with an elasticated back waistband",
      "Flat cotton drawcord with metal tips",
      "Relaxed leg tapering gently to the ankle",
      "Side-seam pockets and one back patch pocket",
      "Garment-washed for softness",
    ],
    material: "100% linen, 210 g/m², garment-washed",
    care: CARE.linen,
    fit: "Relaxed with a tapered leg; take your usual size",
    modelNote: "Model is 186cm and wears M.",
    price: 56_000_00,
    bestsellerRank: 7,
    tags: ["linen", "trousers", "drawstring", "elasticated", "relaxed", "summer", "holiday", "travel", "beach", "weekend"],
    colors: ["tobacco", "sand", "olive"],
    sizes: sizesBetween("s", "xxl"),
    createdAt: "2026-02-18T09:00:00.000Z",
  },

  /* ── Denim ────────────────────────────────────────────────────────────── */
  {
    slug: "relaxed-denim",
    code: "RDN",
    name: "Relaxed Denim",
    category: "denim",
    collections: ["studio-essentials"],
    summary: "A roomy five-pocket jean in rigid Japanese selvedge denim.",
    description:
      "Fourteen-ounce selvedge denim from Okayama, woven on narrow shuttle looms so the clean edge shows when the hem is turned up. The cut is relaxed through the seat and thigh with a gentle taper, sitting just below the natural waist. It starts firm and softens within a few weeks, moulding to the way you move.",
    details: [
      "Relaxed through the seat and thigh with a gentle taper",
      "Mid-to-high rise",
      "Button fly with copper shank buttons",
      "Selvedge outseam, visible when turned up",
      "Hidden rivets at the back pockets",
    ],
    material: "100% cotton selvedge denim, 14 oz, one wash",
    care: CARE.denim,
    fit: "Relaxed with a gentle taper; take your usual waist size",
    modelNote: "Model is 188cm and wears 32.",
    price: 74_000_00,
    bestsellerRank: 6,
    tags: ["denim", "jeans", "selvedge", "japanese", "cotton", "relaxed", "five pocket", "rigid", "casual", "everyday"],
    colors: ["mid-wash", "indigo-rinse", "washed-black"],
    sizes: sizesBetween("w28", "w38"),
    createdAt: "2026-02-03T09:00:00.000Z",
  },
  {
    slug: "carpenter-denim-jacket",
    code: "CDJ",
    name: "Carpenter Denim Jacket",
    category: "denim",
    collections: ["studio-essentials"],
    summary: "A boxy work jacket in heavy denim, with patch pockets and a corduroy collar.",
    description:
      "Built like an old work jacket — boxy, hip-length and generously pocketed — in 13-ounce denim rinsed once to set the colour. The collar is faced in fine corduroy, and the triple-stitched seams will outlast almost anything else in the wardrobe. Worn open over a hoodie, or buttoned over a tee.",
    details: [
      "Boxy, hip-length body",
      "Corduroy-faced collar",
      "Four patch pockets, including a tool pocket at the chest",
      "Triple-needle felled seams",
      "Metal shank buttons",
    ],
    material: "100% cotton denim, 13 oz, rinsed; collar facing 100% cotton corduroy",
    care: CARE.denim,
    fit: "Boxy fit; take your usual size",
    modelNote: "Model is 186cm and wears L.",
    price: 88_000_00,
    tags: ["denim", "jacket", "workwear", "carpenter", "chore", "cotton", "boxy", "casual", "layering"],
    colors: ["indigo-rinse", "ecru"],
    sizes: sizesBetween("s", "xl"),
    createdAt: "2026-05-12T09:00:00.000Z",
  },

  /* ── Tailoring ────────────────────────────────────────────────────────── */
  {
    slug: "tropical-wool-trousers",
    code: "TWT",
    name: "Tropical Wool Trousers",
    category: "tailoring",
    collections: ["harmattan-26"],
    summary: "A lightweight wool trouser with a single pleat, woven open to breathe in the heat.",
    description:
      "Tropical wool is woven in an open plain weave from tightly twisted yarn, which lets air through and helps the cloth spring back from creases. We cut it with a single forward pleat and a softly tapered leg, half-lined to the knee only. The trouser for weddings, dinners and long working days — cooler than most cotton.",
    details: [
      "Mid-to-high rise with a single forward pleat",
      "Tapered leg with a pressed crease",
      "Half-lined to the knee in cupro",
      "Extended waistband with internal brace buttons",
      "Finished with 4cm turn-ups",
    ],
    material: "100% wool, tropical plain weave, 230 g/m²",
    care: CARE.tailoring,
    fit: "Regular through the seat with a tapered leg; take your usual waist size",
    modelNote: "Model is 188cm and wears 32.",
    price: 112_000_00,
    badge: "new",
    tags: ["wool", "tropical wool", "trousers", "tailoring", "pleated", "tapered", "smart", "formal", "wedding", "office", "harmattan"],
    colors: ["slate", "charcoal", "sand"],
    sizes: sizesBetween("w28", "w38"),
    createdAt: "2026-08-24T09:00:00.000Z",
  },
  {
    slug: "tailored-wool-jacket",
    code: "TWJ",
    name: "Tailored Wool Jacket",
    category: "tailoring",
    collections: ["harmattan-26"],
    summary: "A half-canvassed two-button jacket in tropical wool, cut to work with or without its trousers.",
    description:
      "A floating half-canvas chest lets the jacket take on the shape of the wearer over time, rather than holding a rigid form. The shoulder is natural with only a light pad, and the body is half-lined to keep it cool. It matches our tropical wool trousers, but is cut to stand alone over a knit or a band-collar shirt.",
    details: [
      "Single-breasted, two buttons, notch lapels",
      "Floating half-canvas construction",
      "Natural shoulder with light padding",
      "Half-lined in breathable cupro",
      "Working buttonholes at the cuff",
    ],
    material: "100% wool, tropical plain weave, 230 g/m²; lining 100% cupro",
    care: CARE.tailoring,
    fit: "Regular fit, true to size; if between sizes, take the larger",
    modelNote: "Model is 188cm and wears L.",
    price: 185_000_00,
    isFeatured: true,
    tags: ["wool", "tropical wool", "jacket", "blazer", "suit", "tailoring", "two button", "formal", "wedding", "office", "harmattan"],
    colors: ["charcoal", "olive"],
    sizes: sizesBetween("s", "xxl"),
    createdAt: "2026-07-30T09:00:00.000Z",
  },
  {
    slug: "unstructured-linen-blazer",
    code: "ULB",
    name: "Unstructured Linen Blazer",
    category: "tailoring",
    collections: ["coastline"],
    summary: "A soft, unlined linen blazer with patch pockets and no padding.",
    description:
      "No canvas, no shoulder pad and no lining — just a heavy linen, cut and finished so cleanly inside that it doesn't need one. It wears like a shirt, packs into a bag and softens with every wash. Over a tee and drawstring trousers, it still looks considered.",
    details: [
      "Single-breasted, two buttons, notch lapels",
      "Unlined and unpadded, with bound internal seams",
      "Three patch pockets",
      "Horn buttons",
      "Single back vent",
    ],
    material: "100% linen, 280 g/m², garment-washed",
    care: CARE.linenJacket,
    fit: "Relaxed fit; take your usual size",
    modelNote: "Model is 186cm and wears M.",
    price: 148_000_00,
    tags: ["linen", "blazer", "jacket", "unstructured", "unlined", "tailoring", "smart casual", "summer", "wedding", "travel"],
    colors: ["stone", "navy"],
    sizes: sizesBetween("s", "xxl"),
    createdAt: "2026-03-09T09:00:00.000Z",
  },
];
