import { CARE } from "./care";
import { sizesBetween } from "./sizes";
import type { ProductSeed } from "./types";

/** T-shirts, shirts and knitwear. */
export const TOP_SEEDS: ProductSeed[] = [
  /* ── T-shirts ─────────────────────────────────────────────────────────── */
  {
    slug: "heavyweight-boxy-tee",
    code: "HBT",
    name: "Heavyweight Boxy Tee",
    category: "t-shirts",
    collections: ["studio-essentials"],
    summary: "A dense cotton tee cut short and square, with a collar that keeps its shape.",
    description:
      "Knitted from 260 g/m² combed cotton with a dry, faintly matte hand, it stands slightly away from the body and stops cleanly at the hip. The collar is a narrow rib bound at the back neck, so it stays flat wash after wash. Heavy enough to wear alone in the evening; structured enough to sit under an overshirt.",
    details: [
      "Boxy, slightly cropped body with dropped shoulders",
      "Narrow 1.5cm rib collar with self-fabric back-neck tape",
      "Side seams set slightly forward for a clean front line",
      "Twin-needle hems at sleeve and body",
      "Pre-shrunk to within 3% after washing",
    ],
    material: "100% combed cotton jersey, 260 g/m², garment-dyed",
    care: CARE.cottonJersey,
    fit: "Boxy and slightly cropped; take your usual size, or size down for a closer fit",
    modelNote: "Model is 186cm and wears L.",
    price: 28_500_00,
    badge: "restocked",
    isFeatured: true,
    bestsellerRank: 1,
    tags: ["cotton", "jersey", "heavyweight", "boxy", "tee", "t-shirt", "short sleeve", "everyday", "layering", "essential"],
    colors: ["ink", "chalk", "oatmeal"],
    sizes: sizesBetween("xs", "xxl"),
    createdAt: "2026-01-12T09:00:00.000Z",
    updatedAt: "2026-09-02T08:30:00.000Z",
  },
  {
    slug: "oversized-cotton-tee",
    code: "OCT",
    name: "Oversized Cotton Tee",
    category: "t-shirts",
    collections: ["studio-essentials"],
    summary: "A long, generous tee in soft slub cotton, washed for an easy drape.",
    description:
      "Slub yarn gives the jersey a faint, uneven texture that catches the light, and an enzyme wash softens it before it reaches you. The shoulders drop well past their natural line and the sleeves fall to the elbow. Cool enough for midday, and loose enough to sit comfortably over tailored trousers.",
    details: [
      "Oversized body with elbow-length sleeves",
      "Deep dropped shoulder seam",
      "Raised crew neck with a 2cm rib",
      "Back hem 3cm longer than the front",
      "Enzyme-washed for softness from the first wear",
    ],
    material: "100% cotton slub jersey, 200 g/m², enzyme-washed",
    care: CARE.cottonJersey,
    fit: "Oversized by design; size down for a closer fit",
    modelNote: "Model is 183cm and wears M.",
    price: 26_000_00,
    tags: ["cotton", "slub", "jersey", "oversized", "tee", "t-shirt", "short sleeve", "relaxed", "lightweight", "everyday"],
    colors: ["taupe", "washed-black", "bone"],
    sizes: sizesBetween("s", "xxl"),
    createdAt: "2026-01-19T09:00:00.000Z",
  },
  {
    slug: "pima-jersey-long-sleeve",
    code: "PJL",
    name: "Pima Jersey Long Sleeve",
    category: "t-shirts",
    collections: ["studio-essentials"],
    summary: "A fine long-sleeved tee in smooth Peruvian pima cotton.",
    description:
      "Pima's long fibres spin into a smooth, dense yarn, so the jersey has a quiet sheen and resists pilling. It is cut close without clinging, with slim rib cuffs that stay put when pushed up the forearm. Worn alone on cooler evenings, or under a jacket in air-conditioned rooms.",
    details: [
      "Regular fit through the body and sleeve",
      "Slim 1cm rib crew neck",
      "Long rib cuffs that hold when pushed up",
      "Flatlock side seams",
      "Knitted in Peru, finished in our Lagos studio",
    ],
    material: "100% Peruvian pima cotton jersey, 180 g/m²",
    care: CARE.cottonJersey,
    fit: "Regular fit; take your usual size",
    modelNote: "Model is 185cm and wears M.",
    price: 24_000_00,
    compareAtPrice: 32_000_00,
    tags: ["cotton", "pima", "jersey", "long sleeve", "tee", "t-shirt", "regular fit", "layering", "fine"],
    colors: ["ecru", "navy"],
    sizes: sizesBetween("xs", "xl"),
    createdAt: "2026-01-08T09:00:00.000Z",
  },

  /* ── Shirts ───────────────────────────────────────────────────────────── */
  {
    slug: "relaxed-linen-shirt",
    code: "RLS",
    name: "Relaxed Linen Shirt",
    category: "shirts",
    collections: ["coastline"],
    summary: "A loose, washed linen shirt with a soft collar and a slightly longer back.",
    description:
      "Mid-weight European linen, garment-washed until it loses its stiffness and takes on a soft, broken texture. The body is roomy and the collar unlined, so it falls open easily at the neck. It creases, as linen should, and looks better for it by the end of the day.",
    details: [
      "Relaxed body with dropped shoulders",
      "Soft, unlined point collar",
      "Single patch pocket at the chest",
      "Corozo buttons",
      "Curved hem, 3cm longer at the back",
    ],
    material: "100% linen, 185 g/m², garment-washed",
    care: CARE.linen,
    fit: "Relaxed through the body; take your usual size",
    modelNote: "Model is 188cm and wears M.",
    price: 62_000_00,
    isFeatured: true,
    bestsellerRank: 2,
    tags: ["linen", "shirt", "button-up", "long sleeve", "relaxed", "breathable", "lightweight", "summer", "holiday", "beach"],
    colors: ["chalk", "sand", "olive"],
    sizes: sizesBetween("xs", "xxl"),
    createdAt: "2026-02-16T09:00:00.000Z",
  },
  {
    slug: "washed-silk-camp-shirt",
    code: "WSC",
    name: "Washed Silk Camp Shirt",
    category: "shirts",
    collections: ["coastline"],
    summary: "A sand-washed silk shirt with a flat camp collar, made in a single small run.",
    description:
      "Heavy crêpe de chine is sand-washed to take away the shine, leaving a matte, peach-skin surface that moves like water. The camp collar lies flat and the short sleeves are cut full, so air passes through. Made in one small run from a single bolt of cloth.",
    details: [
      "Straight, boxy body with a flat camp collar",
      "Full short sleeves",
      "French seams throughout",
      "Mother-of-pearl buttons",
      "Straight hem with side vents, to be worn untucked",
    ],
    material: "100% silk crêpe de chine, 22 momme, sand-washed",
    care: CARE.silk,
    fit: "Boxy and relaxed; take your usual size",
    modelNote: "Model is 185cm and wears M.",
    price: 78_000_00,
    badge: "limited",
    tags: ["silk", "shirt", "camp collar", "short sleeve", "evening", "occasion", "relaxed", "lightweight", "limited"],
    colors: ["sage", "tobacco"],
    sizes: sizesBetween("s", "xl"),
    createdAt: "2026-06-05T09:00:00.000Z",
    stock: { soldOut: true },
  },
  {
    slug: "poplin-band-collar-shirt",
    code: "PBC",
    name: "Poplin Band-Collar Shirt",
    category: "shirts",
    collections: ["studio-essentials"],
    summary: "A crisp cotton poplin shirt with a clean band collar and concealed placket.",
    description:
      "Two-ply cotton poplin, woven tightly so it stays crisp in the heat and holds a sharp press. The band collar and hidden placket pare the shirt back to its lines — buttoned to the top with tailoring, or worn open over a tee. A slightly shorter body means it looks deliberate untucked.",
    details: [
      "Regular fit with a slightly shortened body",
      "3cm band collar",
      "Concealed button placket",
      "Single-needle stitching throughout",
      "Rounded single-button cuffs",
    ],
    material: "100% two-ply cotton poplin, 120 g/m²",
    care: CARE.cottonWoven,
    fit: "Regular fit; take your usual size",
    modelNote: "Model is 186cm and wears M.",
    price: 52_500_00,
    bestsellerRank: 4,
    tags: ["cotton", "poplin", "shirt", "band collar", "grandad collar", "long sleeve", "crisp", "office", "smart", "regular fit"],
    colors: ["chalk", "pale-blue", "ink"],
    sizes: sizesBetween("xs", "xxl"),
    createdAt: "2026-01-26T09:00:00.000Z",
  },

  /* ── Knitwear ─────────────────────────────────────────────────────────── */
  {
    slug: "knitted-polo",
    code: "KPL",
    name: "Knitted Polo",
    category: "knitwear",
    collections: ["coastline"],
    summary: "A textured cotton-knit polo with an open, buttonless collar.",
    description:
      "Knitted in a fine waffle stitch from mercerised cotton, it has the texture of knitwear and the weight of a shirt. The collar is open, with no placket and no buttons, so it sits flat at the collarbone. Cool on the skin and dry to the touch, even through the afternoon heat.",
    details: [
      "Relaxed fit with a softly ribbed hem",
      "Open camp-style collar, fully fashioned",
      "Waffle-stitch body with plain-knit collar and cuffs",
      "Short sleeves finishing above the elbow",
      "Linked seams for a flat finish",
    ],
    material: "100% mercerised cotton, 12-gauge knit",
    care: CARE.cottonKnit,
    fit: "Relaxed fit; take your usual size",
    modelNote: "Model is 184cm and wears M.",
    price: 64_500_00,
    bestsellerRank: 5,
    tags: ["cotton", "knit", "knitwear", "polo", "short sleeve", "textured", "waffle", "relaxed", "summer", "resort"],
    colors: ["sand", "tobacco", "sage"],
    sizes: sizesBetween("s", "xl"),
    createdAt: "2026-03-20T09:00:00.000Z",
    stock: { soldOutColors: ["sage"] },
  },
  {
    slug: "merino-crewneck",
    code: "MCN",
    name: "Merino Crewneck",
    category: "knitwear",
    collections: ["harmattan-26"],
    summary: "A fine-gauge merino jumper, light enough for a Lagos evening.",
    description:
      "Extra-fine 17.5-micron merino knitted at 16 gauge, so the jumper is thin and smooth enough to wear against the skin. Wool breathes through a warm evening and keeps the chill of an air-conditioned room at bay. Fully fashioned at the shoulder for a close, clean line.",
    details: [
      "Regular fit, close through the shoulder",
      "Fully fashioned shoulders and armholes",
      "Tubular-knit rib at neck, cuffs and hem",
      "Collar linked by hand",
      "Naturally resists odour between wears",
    ],
    material: "100% extra-fine merino wool, 17.5 micron, 16-gauge",
    care: CARE.wool,
    fit: "Regular fit; take your usual size",
    modelNote: "Model is 188cm and wears L.",
    price: 86_000_00,
    badge: "new",
    tags: ["merino", "wool", "knit", "knitwear", "jumper", "sweater", "crewneck", "fine gauge", "layering", "evening", "harmattan"],
    colors: ["ink", "oatmeal", "camel"],
    sizes: sizesBetween("s", "xxl"),
    createdAt: "2026-08-12T09:00:00.000Z",
  },
  {
    slug: "draped-merino-cardigan",
    code: "DMC",
    name: "Draped Merino Cardigan",
    category: "knitwear",
    collections: ["harmattan-26"],
    summary: "A long, buttonless cardigan in fine merino that falls open like a soft jacket.",
    description:
      "Knitted in a fine-gauge merino with a milled finish, so it hangs with the weight of a jacket but breathes like a knit. There are no buttons to fuss with — the long fronts simply fall open and move with you. Worn over a vest or a fine tee, it is the dry-season layer for cool mornings and long evenings.",
    details: [
      "Relaxed fit with softly dropped shoulders",
      "Long, open fronts with no fastening",
      "Milled finish for a smooth, jacket-like drape",
      "Two concealed side-seam pockets",
      "Fully fashioned sleeves with a clean cuff",
    ],
    material: "100% extra-fine merino wool, 14-gauge knit, milled",
    care: CARE.wool,
    fit: "Relaxed fit; take your usual size, or size up for a longer, looser shape",
    modelNote: "Model is 186cm and wears M.",
    price: 98_000_00,
    badge: "new",
    tags: ["wool", "cotton", "knit", "knitwear", "cardigan", "merino", "drape", "open", "layering", "harmattan"],
    colors: ["taupe", "chocolate"],
    sizes: sizesBetween("s", "xl"),
    createdAt: "2026-08-28T09:00:00.000Z",
  },
  {
    slug: "heavyweight-hoodie",
    code: "HHD",
    name: "Heavyweight Hoodie",
    category: "knitwear",
    collections: ["studio-essentials"],
    summary: "A dense loopback-cotton hoodie with a double-layered hood and no drawcord.",
    description:
      "Loopback cotton at 420 g/m² gives the hoodie real weight and a structured drape, while the looped reverse keeps it breathable. The hood is double-layered, so it holds its shape without a drawcord. Only lightly brushed inside — soft, but not so warm that it only works in the cold.",
    details: [
      "Relaxed fit with dropped shoulders",
      "Double-layered hood, no drawcord",
      "Kangaroo pocket with bartacked corners",
      "Ribbed cuffs and hem with a little stretch for recovery",
      "Flatlock seams throughout",
    ],
    material: "100% cotton loopback, 420 g/m²; rib trims 95% cotton, 5% elastane",
    care: CARE.cottonJersey,
    fit: "Relaxed fit; take your usual size",
    modelNote: "Model is 183cm and wears L.",
    price: 58_500_00,
    tags: ["cotton", "loopback", "fleece", "hoodie", "sweatshirt", "heavyweight", "relaxed", "casual", "weekend", "layering"],
    colors: ["washed-black", "charcoal", "oatmeal"],
    sizes: sizesBetween("xs", "xxl"),
    createdAt: "2026-07-14T09:00:00.000Z",
  },
];
